name: Deploy Blazor Website

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore
      run: dotnet workload restore

    - name: Install Dart
      run: |
        curl -LJO https://github.com/sass/dart-sass/releases/download/1.77.2/dart-sass-1.77.2-linux-x64.tar.gz
        tar -xzf dart-sass-1.77.2-linux-x64.tar.gz
        sudo mv dart-sass/* /usr/local/bin/

    - name: Compile SCSS
      run: sass wwwroot/css:wwwroot/css
      
    - name: Publish Website
      run: dotnet publish Portfolio-Website.csproj -c Release -o publish
      
    - name: Initialise docs
      run: |
        mkdir -p docs
        rm -rf docs/*

    - name: Generate CNAME File
      run: echo "www.scottytatham.com" > docs/CNAME
      
    - name: Deploy To docs/
      run: |
        cp -r publish/wwwroot/* docs/
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto Deploy" || echo "Auto Deploy"
        git push origin main
