name: Deploy Blazor Website

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore
      run: dotnet workload restore

    - name: Compile SCSS
      uses: gha-utilities/sass-build@v0.6.1
      with:
        source: wwwroot/css/**/*.scss
        destination: .
      
    - name: Publish Website
      run: dotnet publish Portfolio-Website.csproj -c Release -o publish
      
    - name: Creat docs If Required
      run: mkdir -p docs
      
    - name: Deploy To docs/
      run: |
        rm -rf docs/*
        cp -r publish/wwwroot/* docs/
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto Deploy" || echo "Auto Deploy"
        git push origin main
